### ISSUE TITLE
Being able to customize the field that is updated on confirm

### ISSUE THREAD

**Issue by Vayel** [LeoneBacciu/django-email-verification#1]
Hello!

Currently, when we send an email confirmation or receive a valid token, we update the field `get_user_model().is_active` (https://github.com/LeoneBacciu/django-email-verification/blob/master/django_email_verification/Confirm.py#L32).

It would be convenient to be able to customize that field name (e.g. updating `get_user_model().is_email_active`). Indeed, user activation may depend on other conditions (phone verification for instance).

Thanks.

**Comment by DavidJayBrady** [comment]
Hey @Vayel , it can actually already do this. I extended AbstratUser in my project, created a new field called `email_verified`, and then changed the `EMAIL_ACTIVE_FIELD` to `email_verified`. Works the exact same but on this different field
