### ISSUE TITLE
Where do you put the email templates?

### ISSUE THREAD

**Issue by rgill02** [LeoneBacciu/django-email-verification#10]
Where are you supposed to the put the templates shown in the example? I keep getting a "TemplateDoesNotExist" exception.

**Comment by alesanco** [comment]
The code uses the **render_to_string** method. This method uses TEMPLATES settings to get template files.

Take a look here: https://docs.djangoproject.com/en/3.0/topics/templates/

Hope this helps!

**Comment by rgill02** [comment]
It did! Thank you! And for anyone else who might have the same issue I put the templates inside a "templates" directory inside my project directory and then modified the templates settings in the settings.py file like so
`'DIRS': [os.path.join(BASE_DIR, 'templates')],`

**Comment by Genarito** [comment]
It'd be cool to have this explanation in the README! Thank you!
