### ISSUE TITLE
Email sends "Error, invalid token! "

### ISSUE THREAD

**Issue by YDA93** [LeoneBacciu/django-email-verification#13]
I am using UserCreationForm and I removed username so I only use email as usename.

I cant run the below code:
user = get_user_model().objects.create(username=username, password=password, email=email)

My view.py:

def signup_view(request):
    if request.user.is_authenticated:
        return redirect('account')

    form = SignupForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            result_json = captcha_validation(request, "signup_recaptcha")
            if not result_json.get('success') or (result_json["score"] <= 0.5):
                messages.info(request, 'Failed to verify ReCaptcha.')
            elif result_json.get('success') and (result_json["score"] >= 0.5):
                user = form.save(commit=False)
                user.is_active = False  # Deactivate account till it is confirmed
                user.save()

                username = request.POST.get('email')
                password = request.POST.get('password')
                email = request.POST.get('email')
                user = (username, password, email) ##Here is my problem i tried this since i cant create object
                sendConfirm(user)

                messages.success(request, 'Account successfully created')
                return redirect('login')

    context = {"title": "Signup", "form": form}
    return render(request, 'accounts/signup.html', context)

------------------

Would appreciate your feedback and help

**Comment by LeoneBacciu** [comment]
Are you using a custom user model? If yes, can you share it?

**Comment by LeoneBacciu** [comment]
Have you solved? Can I close this issue?

**Comment by DGathagu** [comment]
> Have you solved? Can I close this issue?

How do we make this work with a custom user model?

**Comment by LeoneBacciu** [comment]
You have to add a [custom user model in the settings.py](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#substituting-a-custom-user-model).

**Comment by dhargreaves** [comment]
I'm also having this issue. I've created a very simple custom user model that inherits from AbstractUser and adds just a single additional field. Custom user model is declared in the settings file. Everything else relating to the custom user model is working fine and email sends out ok but tried with a couple of different accounts and still get an invalid token error.

_models.py_
`class CustomUser(AbstractUser):
    description = models.CharField(max_length=250, default='')
    def __str__(self):
        return self.username`

_settings.py_
`AUTH_USER_MODEL = 'accounts.CustomUser'`

_views.py_
`def SignUpView(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password, email=email)
            sendConfirm(user)
            login(request, user)

            return redirect('signup')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})`

**Comment by LeoneBacciu** [comment]
From the code you submitted it seems like you are not creating the user (es: `CustomUser(username=username, password=raw_password, email=email)`). Is it correct?

**Comment by dhargreaves** [comment]
No, the user does get created. I can see the user in admin but the user is not active.

**Comment by YDA93** [comment]
Good day all!
This is how i solved it:
signup_form = SignupForm(request.POST or None)
user = signup_form.save(commit=False)
user.is_active = False  # Deactivate account till it is confirmed
user.save()


---------------------- 

Signup form is inherited from UserCreationForm made in forms.py:

**Comment by YDA93** [comment]
> No, the user does get created. I can see the user in admin but the user is not active.

You can make the user active before saving the form like this:
user.is_active = True
user.save()

**Comment by dhargreaves** [comment]
> > No, the user does get created. I can see the user in admin but the user is not active.
> 
> 
> 
> You can make the user active before saving the form like this:
> 
> user.is_active = True
> 
> user.save()
> 
> 

It’s correct for user not to be active as my understanding is that when sendConfirm is called a user becomes inactive and when user clicks on email link this should switch user to active rather than having to include it in code. 

I feel like I must be missing something here or that the custom user model I’ve created is incompatible with the package somehow.

**Comment by YDA93** [comment]
Ok i will start one by one here:
First step:

create a function to hash url based on (username or user-email) + user.id + timestamp:
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from six import text_type

class AppTokenGenerator(PasswordResetTokenGenerator):
    """ Inherited from PasswordResetTokenGenerator """

    def _make_hash_value(self, user, timestamp):
        return text_type(user.is_active) + text_type(user.pk) + text_type(timestamp)


account_activation_token = AppTokenGenerator()

Second Step:
Upon registration make sure user is inactive, Then generate the URL and send the e-mail:
This is my view:
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
 signup_form = SignupForm(request.POST or None)
if signup_form.is_valid():

                user = signup_form.save(commit=False)
                user.is_active = False  # Deactivate account till it is confirmed
                user.save()
                email = signup_form.cleaned_data.get('email')
                email_body = {
                    'user': user,
                    'domain': get_current_site(request).domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                }

                link = reverse('activate', kwargs={
                    'uidb64': email_body['uid'], 'token': email_body['token']})

                html_message = render_to_string(
                    'mail/activation.html',
                    {'activate_url': 'https://'+get_current_site(request).domain+link})

                send_email(html_message, email, 'Activate your account')

Third Step:
To activate the user using different view:
def activate(request, uidb64, token):
    """ Activate user from link sent to email post registration """
    user_id = force_text(urlsafe_base64_decode(uidb64))
    user = CustomUser.objects.get(pk=user_id)

    if not account_activation_token.check_token(user, token):
        return redirect('home')

    if user.is_active:
        return redirect('home')
    user.is_active = True
    user.save()
    messages.success(
        request, 'Account activated successfully.', extra_tags="activation")
    return redirect(login_view)

**Comment by dhargreaves** [comment]
@YDA93 I’ve worked through the code above and have it working now. Thanks for your help.
