### ISSUE TITLE
Password reset integration

### ISSUE THREAD

**Issue by FransStreicher** [LeoneBacciu/django-email-verification#15]
Hi, I'd like to include password reset integration into this library. I'm currently working on my own fork and expanding functionality to include this. I'd like to know whether it's something you might want to include in your repository in future, if not, would you like your authorship to stay with the new pip package I will create that contains a modified version of django-email-verification but with in built password-reset functionality as well? I ask this because I don't want to modify things and include your author name in the docs if you dont want your name associated with it.

**Comment by LeoneBacciu** [comment]
This is interesting.
If you want to give me more details feel free to write to my personal email.
In any case it's ok if you include my author name.
