### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by sebbelese** [LeoneBacciu/django-email-verification#19]
Hi,

django-email-verification works perfectly on my website, readme is very clear & complete.

However, the email template is sent using the default language (no translation performed), and the token link redirects to the page in the default language (e.g. in my case _/en/accounts/email/[token]_) even if it was generated from a page in a different language.

Is there any support for internationalization or possibility to customize the link and email depending on the currently set language?

**Comment by Stratoff** [comment]
Hello, I'd like to add **another problem** about translations here.

I have the same issue of @sebbelese, it always redirect to the default language in the token link, also, when I try to add internationalization to the EMAIL_MAIL_SUBJECT field I got the following error:

`django_email_verification.errors.NotAllFieldCompiled: Field EMAIL_MAIL_SUBJECT missing or invalid`

This is my code in **settings.py:**

`from django.utils.translation import ugettext_lazy as _`
.
.
`EMAIL_MAIL_SUBJECT = _('Confirme su cuenta de correo electronico')`

**Is there any support for internationalization of the email subject?**

**Comment by sebbelese** [comment]
I have this too but used a subject that works in both languages I use.

**Comment by LeoneBacciu** [comment]
Since version 0.1.0 the context of the templates contains the `user` object which can be used to determine the language and translate using the template tags. I think the [documentation](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#internationalization-in-template-code) should help with it.
