### ISSUE TITLE
Refresh activation token

### ISSUE THREAD

**Issue by dittrash** [LeoneBacciu/django-email-verification#20]
the activation mechanism works flawlesly, but sometimes if the user doesn't click the link for a while (maybe 10 minutes or so) the token gets expired and the link returns "Error, invalid token". Is there any way to solve this problem without re-register the user's account?. I found nothing like it in the docs.

**Comment by LeoneBacciu** [comment]
Thank you! It has now been fixed.
Since version `0.1.0`  you can manually set the token lifespan with the `EMAIL_TOKEN_LIFE` parameter in the settings.

**Comment by dittrash** [comment]
That's awesome!!!!!
Thank you so much.
