### ISSUE TITLE
SPAM FOLDER

### ISSUE THREAD

**Issue by sample114** [LeoneBacciu/django-email-verification#21]
Emails going to spam folder

**Comment by Genarito** [comment]
I think it's not a problem of this library: the policy of SPAM emails depends on every provider, Gmail has not the same policy than Outlook. To prevent this issue you should ensure that emails are send from a secure host, i.e. a one with a certificate for TLS encription from a registred governmental entity. Also there are some extra important considerations: you can read [this](https://sendpulse.com/blog/prevent-emails-landing-spam-folder) or [this](https://coherentpath.com/rarelogic/blog/how-to-prevent-emails-from-going-to-spam/)
