### ISSUE TITLE
Error Invalid Token

### ISSUE THREAD

**Issue by millerthegorilla** [LeoneBacciu/django-email-verification#23]
Hi,

I am getting 'Error Invalid Token' using this app.

I have traced through the code involved, and default_token_generator.check_token(user, token) is working immediately after the token is made, but later on, when the same function is called in your function VerifyToken, with the same user, and the same token, the function returns false.
Internally the default_token_generator.check_token is calculating the timestamp of the token, and then calling a function make_token_with_timestamp (https://github.com/django/django/blob/2d6179c819010f6a9d00835d5893c4593c0b85a0/django/contrib/auth/tokens.py#L72) and is comparing the two tokens.
The check fails because the hash for the user password field has changed.

In the file confirm.py in the function sendConfirm, the following:

        except KeyError:
            token = default_token_generator.make_token(user)
            print("user.password",user.password)

prints :  user.password pbkdf2_sha256$216000$g4lediz0jaqK$lOn2Gmc6hd1p7sYJwqgFKfEwlvWS7dS80f/7cf8Vt28=

and in the function verifyToken, the following:

        for user in users:
            print("user.password", user.password)
            valid = default_token_generator.check_token(user, email_token)

prints: user.password pbkdf2_sha256$216000$WsCFWBnNnlyA$hY1/sbrtOv6ifGB0XwK73bRIAUTRz3hcrX9NrRxeLDA=

Clearly, the hash for the password field has changed, although I have no idea why that might be the case.
Because the hash has changed, the code in django/contrib/auth/tokens.py

            if not constant_time_compare(self._make_token_with_timestamp(user, ts), token):
            # RemovedInDjango40Warning: when the deprecation ends, replace
            # with:
            #   return False
            if not constant_time_compare(
                self._make_token_with_timestamp(user, ts, legacy=True),
                token,
            ):
                return False

returns false, and so the verifyToken function in Confirm.py fails.

I am using a postgres backend, but have tested using the sqlite backend with the same result.

**Comment by millerthegorilla** [comment]
I have checked by making a user and clicking the link, and by making a user and not clicking the link.   In both cases, I used the admin panel to activate the users.   The first user was unable to login, whilst the second user was able to login.  I am certain that this is because the user password changes at some point after clicking the link in the email.

**Comment by millerthegorilla** [comment]
I have figured it out. In my register view, I was calling the function to make_token and send email, before I called the registerView.super.
So, I changed this:

def form_valid(self, form):
    user = form.save()
    sendConfirm(user)
    return super(RegisterView, self).form_valid(form)

To this:

def form_valid(self, form):
    user = form.save()
    bob = super(RegisterView, self).form_valid(form)
    sendConfirm(user)
    return bob

Internally, the sendConfirm is using a threaded function to send the email, and by the time the super class had been called, the link was sent with a password that was then overwritten by the threaded function.
I will, of course, change bob to a more meaningful name…

**Comment by millerthegorilla** [comment]
was my pull request that unsatisfactory?   Also, I have discovered that if I comment out the django-email-verification in 'installed apps' in settings.py, django-email-verification continues to work.

**Comment by LeoneBacciu** [comment]
It was everything but unsatisfactory! I haven't merged it sooner because there was a missing colon and I decided to refactor it a little bit. I've just merged it into master and published it as `django-email-verification==0.0.8`.
Thank you for the contribution!
