### ISSUE TITLE
README.md on Github's dark theme

### ISSUE THREAD

**Issue by qcoumes** [LeoneBacciu/django-email-verification#25]
Not really a big issue, but the color palette used by the image in the README.md does not render well on Github's dark theme.

Here how it looks:

![Screenshot from 2021-01-19 16-58-44](https://user-images.githubusercontent.com/24588090/105059641-cead3d00-5a77-11eb-9e66-52902d260f42.png)

As you can see, it's quite hard seeing most lines.

**Comment by LeoneBacciu** [comment]
Thank you! Solved in 7ad9c910e332b6be3840efc5013c694fe9aae838.
