### ISSUE TITLE
pytest tests

### ISSUE THREAD

**Issue by millerthegorilla** [LeoneBacciu/django-email-verification#27]
Hi, thanks for your work on django-email-verification.

I am new to pytest, but have managed to run tests using the command 
```
pytest --pyargs django_email_verification  ...
```
but several tests fail because of a missing template 'confirm.html'.  Is there a way of passing in a string or path to the variable 'template_name' in the test?

many thanks.

**Comment by LeoneBacciu** [comment]
You are right, pypi doesn't automatically include files other than `.py`.
If you want to run the tests, just clone the repo.
I am not sure if including the tests in the package is considered a best practice, is it?
