### ISSUE TITLE
Different users with same email

### ISSUE THREAD

**Issue by ronaldowg** [LeoneBacciu/django-email-verification#29]
Great package!

How to handle multiple users with same e-mail?
During token verification (django_email_verification/token.py) line 81, a user is filtered just considering his email. Could we filter by username and email?

"raise self.model.MultipleObjectsReturned(
accounts.models.CustomUser.MultipleObjectsReturned: get() returned more than one CustomUser -- it returned 2!"

Thanks.

**Comment by LeoneBacciu** [comment]
This feature will be implemented in the next release coming up soon. Look at #26

**Comment by LeoneBacciu** [comment]
The latest version of the library supports this feature again!
