### ISSUE TITLE
Test against/add support for Django 3.2

### ISSUE THREAD

**Issue by hirusi** [LeoneBacciu/django-email-verification#37]
Hello! Django 3.2 was [released on April 6, 2021](https://docs.djangoproject.com/en/3.2/releases/3.2/). It would be much appreciated if the new release is supported.

**Comment by LeoneBacciu** [comment]
Thanks for the suggestion.
With the last release [0.1.1rc0](https://pypi.org/project/django-email-verification/0.1.1rc0/) the latest version of Django is supported.
