### ISSUE TITLE
Extend a view from verification view

### ISSUE THREAD

**Issue by zOthix** [LeoneBacciu/django-email-verification#39]
My use case required me to do some extra steps when user is verified, how can i do that? 
i want to be able to extend the verification view, so after verification i can do some other stuff in that view

**Comment by LeoneBacciu** [comment]
Thanks for the suggestion!
With the latest release [0.1.1rc0](https://pypi.org/project/django-email-verification/0.1.1rc0/) is now possible to do so.
Please check out [the readme](https://github.com/LeoneBacciu/django-email-verification#token-verification).
Hope it helps
