### ISSUE TITLE
Can not send the activations email

### ISSUE THREAD

**Issue by The-Daishogun** [LeoneBacciu/django-email-verification#44]
Hello.
i was trying to manually verify and redirect the user to another page if their token is valid but after adding the custom verify view, the package can't send the verification email.

#### the error
```python
File "/usr/local/lib/python3.8/site-packages/django_email_verification/confirm.py", line 51, in <listcomp>
     d = [v[0][0] for k, v in get_resolver(None).reverse_dict.items() if has_decorator(k)]
   File "/usr/local/lib/python3.8/site-packages/django_email_verification/confirm.py", line 49, in has_decorator
     return k.__dict__.get('django_email_verification_view_id', False)
AttributeError: 'str' object has no attribute '__dict__'
```

#### the view:
```python
@verify_view
def confirm(request, token):
    success, user = verify_token(token)
    if success == True:
        return redirect("http://example.com")
```
#### urls.py:
```python
urlpattersm = [
      path("email/<str:token>/", views.confirm),
]
```

as far as i can tell, `has_decorator(k)` expects k to be a function but i've checked and there are strings in the output of `get_resolver(None).reverse_dict.keys()` so when it tries to check those strings, it fails.
perhaps adding an `isinstance()` to check if k is a function or a string to `has_decorator()` will do the trick(?)

#### output of `get_resolver(None).reverse_dict.keys()`, `django_version==3.1.6`:
```
[<function confirm at 0x7fabce938d30>, 'email_verify',
 <function WrappedAPIView at 0x7fabace68550>, 'verify', 
<function WrappedAPIView at 0x7fabace68280>, 'request',
<function WrappedAPIView at 0x7fabd1cdc8b0>, 'change_accept',
 ...]
```

**Comment by LeoneBacciu** [comment]
Can you share the view which makes `k` a string?
I can't replicate and I need to for testing purposes.
Thanks!

**Comment by The-Daishogun** [comment]
i'm afraid since this is from a commercial project and bc of of NDAs and such i can't share the codes with you but from my understanding, these string variables are the value of the `name` argument of the `django.urls.path` . i could recreate the scenario by adding this argument to the `path`s in `urls.py` but the weird thing is that only some of the names actually showed up in the results of `get_resolver(None).reverse_dict.keys()`.
the changes i temporarily made for reproducing the problem are the following:
```python
# django_email_verification/urls.py
urlpatterns = [
    path('<str:token>', verify, name="test1") # shows up as a string in the dict
]
---------------------------------------
# django_email_verification/tests/urls.py
urlpatterns = [
    path('email/', include(urls), name="test2"), # does not show up 
    path('confirm/', verify_view(lambda request: None), name="test3"), # shows up as a string in the dict
]
--------------------
# all other django.urls.path in django_email_verification/tests/url_test1.py
#  and django_email_verification/tests/url_test2.py won't show up as strings
```
the simplest way to check:
```
$ python
>>> import django
>>> django.setup()
>>> from django.urls import get_resolver
>>> get_resolver(None).reverse_dict.keys()
# output: dict_keys([<function <lambda> at 0x7f42ee349e50>, 'test3', <function verify at 0x7f42ee2ebaf0>, 'test1'])

**Comment by LeoneBacciu** [comment]
Thank you for providing more detail!
I added the test on dcfb970ca0ae39ab738a1b6c5b7ecb7c86c4865c.
The package is now published as a release candidate with the version [0.1.1rc1](https://pypi.org/project/django-email-verification/0.1.1rc1/).
