### ISSUE TITLE
The user model you provided is invalid

### ISSUE THREAD

**Issue by Jayvijay422000** [LeoneBacciu/django-email-verification#46]
the code runs perfectly on localhost
but doesn't work in the production environment
pls help

**Comment by LeoneBacciu** [comment]
Can you please provide more info?

**Comment by The-Daishogun** [comment]
> the code runs perfectly on localhost
> but doesn't work in the production environment
> pls help

is it possible you forgot to set the `settings.EMAIL_PAGE_DOMAIN` to the domain of your production environment?
