### ISSUE TITLE
defining a method on AUTH_USER_MODEL instead of EMAIL_VERIFIED_CALLBACK

### ISSUE THREAD

**Issue by The-Daishogun** [LeoneBacciu/django-email-verification#47]
Hello.
this is more of a suggestion than it is an issue but since EMAIL_VERIFIED_CALLBACK function always receives the user as an argument i thought of defining it as a method on the AUTH_USER_MODEL instead a separate function dedicated to doing this. and then just calling that method.

we can check if the method is defined or not and if it is not defined, do the default callback which is just `is_active = True`.
https://github.com/LeoneBacciu/django-email-verification/blob/bd62e9dc782ad65706dc21b7cb23033666b1d410/django_email_verification/confirm.py#L96

the pros of doing this (that i can think of) is that the logic is now contained within the user object and therefore it is easier to maintain.
the only problem i can think of is that it forces the package user to define a custom user model if they want to customize the behavior (though i think most people usually do).

if you think this is a worthwhile addition to this package, I'd be happy to  make a pull request for this.
thank you.

**Comment by LeoneBacciu** [comment]
Thanks for the idea, it might be a worthwhile update.
I think however that the developer shouldn't be forced to have a custom user model, so we should keep the current approach as a fallback. Feel free to make a pull request if you want 😉
Thanks again

**Comment by The-Daishogun** [comment]
Added in #50
