### ISSUE TITLE
ImportError: cannot import name 'verify_view' from 'django_email_verification'

### ISSUE THREAD

**Issue by bhushnapatil** [LeoneBacciu/django-email-verification#54]
Hello, first of all awesome library. I am trying to extend the view as I want to do some more stuff after the email is verified. I tried to import the `verify_view` from the `django_email_verification` although I am getting an error that the library does not contain `verify_view`. I read the documentation where you mentioned `The library makes sure one and only one @verify_view is present and throws an error if this condition is not met.`, I am not quit sure I was able to understand it, as I do not contain any function or view named verify_view in my library. Below you can find the source code of the file. Thanks in advance.

```
from django.http import HttpResponse
from django_email_verification import verify_token, verify_view


@verify_view
def verify_email(request, token):
    success, user = verify_token(token)

    if success:
        //do something

    return HttpResponse(f'Account verified, {user.email}' if success else 'Invalid token')
```

The Error

```
  File "/home/bhushan/Documents/Projects/Repo/Django/application/application/users/views.py", line 10, in <module>
    from django_email_verification import verify_view, verify_token
ImportError: cannot import name 'verify_view' from 'django_email_verification' (/home/bhushan/Documents/Projects/Repo/Django/application/env/lib/python3.8/site-packages/django_email_verification/__init__.py)
```

I also checked in the library there was nothing named as `verify_view`.  Am I doing something wrong here?

**Comment by wenbodu971228** [comment]
Same problem, I just installed with pip install django_email_verification==0.1.1rc and it works. Seems it Github readme is different from pip ones.

**Comment by bhushnapatil** [comment]
Yeah its working now, thanks @wenbodu971228.
