### ISSUE TITLE
TypeError when sending email

### ISSUE THREAD

**Issue by ElliottDenlinger** [LeoneBacciu/django-email-verification#59]
Python=3.10.3
django-email-verification=0.2.2

We recently upgraded `django-email-verification` from the last RC version to the new 0.2.2 and are receiving an error when sending the email. [This line](https://github.com/LeoneBacciu/django-email-verification/blob/master/django_email_verification/confirm.py#L68) throws `TypeError: can only concatenate str (not "bytes") to str` when trying to concat the token with the rest of the string. The token value comes in as bytes in the form `b'tokenvalue'`. 

I'm unsure if this is a configuration issue on our end with the new version or not. 

Thanks!

**Comment by ibtsam0018** [comment]
same issue

**Comment by tabebqena** [comment]
same issue
