### ISSUE TITLE
Attached static files on Email

### ISSUE THREAD

**Issue by wozniakos10** [LeoneBacciu/django-email-verification#60]
Hi, thanks for create this awesome library. I have one question about this package. I tried to customize mail_body html and send to user a message with image which i have in static files on my project. I use it on that way:
```bash
img src="{% static 'msagh_website/images/agh.jpg' %}"
```

And mail comes to use without a image. When i use this syntax to display image on my site everything is ok. When instead of this syntax I just use url from random image on net, there is no problem.

**Comment by LeoneBacciu** [comment]
This is likely because the generated url is relative (e.g. `/images/cat.png`) instead of absolute (e.g. `https://example.com/images/cat.png`). You should manually add the domain name of the server where the image is stored, so that the email client can figure out where to take the image from.
