### ISSUE TITLE
Dependencies missing on PyPi?

### ISSUE THREAD

**Issue by oalmelid** [LeoneBacciu/django-email-verification#61]
Apologies if this has been answered elsewhere. I just installed django-email-verification using pipenv in my django project, and it looks like all package requirements might be missing from the latest release? Running pip show after install shows the following

```
bash$ pip show django-email-verification
Name: django-email-verification
Version: 0.2.2
Summary: Email confirmation app for django
Home-page: https://github.com/LeoneBacciu/django-email-verification
Author: Leone Bacciu
Author-email: leonebacciu@gmail.com
License: MIT
Location: /Users/oalmelid/.local/share/virtualenvs/web-portal-yvG0OUvE/lib/python3.8/site-packages
Requires: 
Required-by: 
```

Attempting to add the module to my project fails after PyJWT is not found.

**Comment by rokn** [comment]
Happens here as well with miniconda, Python 3.9  and pip 21.2.4

**Comment by LeoneBacciu** [comment]
The best solution for now is to install the latest version of PyJWT manually. Sorry for the inconvenience.
Please let me know if this fixes it.

**Comment by DylanCheetah** [comment]
I had the same issue, and I can confirm that manually installing PyJWT fixes the problem.
