### ISSUE TITLE
Specify a from email different than the sender email

### ISSUE THREAD

**Issue by julianpacker** [LeoneBacciu/django-email-verification#7]
Currently the from email used is the sender, but if I want to use an alias address that isn't possible. I could fork the project and create this request myself?

Also the field EMAIL_MAIL_PLAIN is mandatory despite mentioning it isn't, even if it is unused. Without the argument, this line fails: text = render_to_string(mail_plain, {'link': link}), because mail_plain is None. To clarify I do have EMAIL_MAIL_HTML properly set.

Also, I noticed a print statement lying around, can we remove that? Line 86: Confirm.py

**Comment by subodhk01** [comment]
@julianpacker Great work in finding these issues! Yeah sure if you want to work on these issues, go ahead that would be wonderful!
If you need any help or want us to work on something else just ping here.

**Comment by julianpacker** [comment]
I just saw John's latest commit adds this functionality. Although it doesn't work for me (not sure why). I specify a from address and it seems the the SMTP server package ignores it.

In addition, I didn't get that error with the cloned repo. So a new version of this package would fix those issues. That print statement on line 93 is still there but that's not worth a pull request.

**Comment by DavidJayBrady** [comment]
Hi,

was the issue about EMAIL_MAIL_PLAIN still being mandatory when EMAIL_MAIL_HTML is set resolved? I wasn't able to send the link via html but it worked fine once I switched to just using EMAIL_MAIL_PLAIN

**Comment by julianpacker** [comment]
I see it's resolved on the master branch, that's why I closed the issue. When I pulled this locally it all worked fine. The next version of this package will have the change you need.

Also the reason the from address wasn't working for me was possibly because I was using Google's SMTP server which doesn't support a different from address.
